[project]
version = "0.1.0"
name = "carrier"
cincludes = []
cobjects = [
    "3rdparty/libbase58/base58.c",
    "3rdparty/hacl-star/snapshots/hacl-c/FStar.c",
    "3rdparty/hacl-star/snapshots/hacl-c/kremlib.c",
    "3rdparty/hacl-star/snapshots/hacl-c/Hacl_Ed25519.c",
    "3rdparty/hacl-star/snapshots/hacl-c/Hacl_Curve25519.c",
    "3rdparty/hacl-star/snapshots/hacl-c/Hacl_SHA2_256.c",
    "3rdparty/hacl-star/snapshots/hacl-c/Hacl_HMAC_SHA2_256.c",
    "3rdparty/hacl-star/snapshots/hacl-c/Hacl_Chacha20Poly1305.c",
    "3rdparty/hacl-star/snapshots/hacl-c/Hacl_Chacha20.c",
    "3rdparty/hacl-star/snapshots/hacl-c/AEAD_Poly1305_64.c",
    "3rdparty/hacl-star/snapshots/hacl-c/Hacl_Policies.c",
]
pkgconfig = []
cflags = [ "-D", "KRML_NOUINT128", "-Os"]
lflags = []
asan = false

[dependencies]
err         = "1"
hex         = "1"
std         = "1"
byteorder   = "1"
hpack       = "1"
net         = "1"
string      = "1"
json        = "1"
log         = "1"
protonerf   = "1"
pool        = "1"
toml        = "1"
fs          = "1"

[variants]
default = []

[[artifacts]]
name = "carrier"
type = "lib"
main = "carrier"

[[artifacts]]
name = "carrier"
type = "staticlib"
main = "carrier"

[[artifacts]]
name = "carrier"
type = "exe"
main = "carrier::main"

[[artifacts]]
name = "carrier"
type = "npm"
main = "carrier::mission"
